/**
 * This file was autogenerated from maincharacter.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _maincharacter_h_
#define _maincharacter_h_
//---------------------------------------------------------------------------------
extern const unsigned char maincharacter[];
extern const int maincharacter_size;
//---------------------------------------------------------------------------------
#endif //_maincharacter_h_
//---------------------------------------------------------------------------------
